# Generated by Django 3.1.7 on 2021-04-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_remove_userprofile_user_address'),
        ('customer_address', '0002_customeraddress_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='addresstype',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
    ]
