# Generated by Django 3.1.7 on 2021-07-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_address', '0003_auto_20210422_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='addresstype',
            field=models.CharField(default='home', max_length=255),
        ),
    ]
