# Generated by Django 3.1.7 on 2021-04-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='mobile_no',
        ),
    ]
