# Generated by Django 3.1.7 on 2021-04-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_userprofile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='token',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
